using System.Security.Cryptography;
using ZScout.HwTest.Contracts.Models;

namespace ZScout.HwTest.App.Auth;

/// <summary>
/// Runs once at startup. If no user accounts exist in the store, creates a
/// default Admin account so the dashboard is accessible out-of-the-box.
///
/// Password resolution order:
///   1. Auth:DefaultAdminPassword configuration key (set via
///      Auth__DefaultAdminPassword environment variable in docker-compose.yml)
///   2. Auto-generated random 16-character password printed to the log once.
///
/// After first login, change the password or create a new account via the
/// Settings page and remove Auth__DefaultAdminPassword from the environment.
/// </summary>
public sealed class DefaultAdminSeedService : IHostedService
{
	private readonly IUserStore _userStore;
	private readonly IConfiguration _config;
	private readonly ILogger<DefaultAdminSeedService> _logger;

	public DefaultAdminSeedService(
		IUserStore userStore,
		IConfiguration config,
		ILogger<DefaultAdminSeedService> logger)
	{
		_userStore = userStore;
		_config = config;
		_logger = logger;
	}

	public async Task StartAsync(CancellationToken cancellationToken)
	{
		var existing = await _userStore.GetAllAsync(cancellationToken);
		if (existing.Count > 0)
			return;

		var configuredPassword = _config["Auth:DefaultAdminPassword"];
		string password;
		bool autoGenerated;

		if (!string.IsNullOrWhiteSpace(configuredPassword))
		{
			password = configuredPassword;
			autoGenerated = false;
		}
		else
		{
			password = GeneratePassword();
			autoGenerated = true;
		}

		var now = DateTimeOffset.UtcNow;
		var account = new UserAccount
		{
			UserId = Guid.NewGuid().ToString("N"),
			Username = "admin",
			PasswordHash = LocalAuthService.HashPassword(password),
			Role = UserRole.Admin,
			IsActive = true,
			CreatedAtUtc = now,
			UpdatedAtUtc = now
		};

		await _userStore.UpsertAsync(account, cancellationToken);

		if (autoGenerated)
		{
			// Log at Warning level so it stands out in production log streams.
			_logger.LogWarning(
				"No user accounts found. Created default admin account. " +
				"Username: admin  Password: {Password}  " +
				"Change this password via Settings after first login.",
				password);
		}
		else
		{
			_logger.LogInformation(
				"No user accounts found. Created default admin account from " +
				"Auth:DefaultAdminPassword configuration. Username: admin");
		}
	}

	public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;

	private static string GeneratePassword()
	{
		const string chars = "abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ23456789!@#$";
		return string.Create(16, chars, static (span, alphabet) =>
		{
			Span<byte> bytes = stackalloc byte[16];
			RandomNumberGenerator.Fill(bytes);
			for (int i = 0; i < span.Length; i++)
				span[i] = alphabet[bytes[i] % alphabet.Length];
		});
	}
}
